### PR TITLE
Symfony 6 support

### LINKED ISSUE #90: Symfony 6.0 support
Flagception does not list compatibility with Symfony 6.0.

I'm not seeing any deprecation messages when running flagception-bundle 4.1 on Symfony 5.4, so it probably doesn't need any code changes -- just a composer tweak.

This is the error I get when trying to update to Symfony 6.0 in a project that uses flagception-bundle:

```
$ composer update
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires flagception/flagception-bundle ^4.1 -> satisfiable by flagception/flagception-bundle[4.1.0].
    - flagception/flagception-bundle 4.1.0 requires symfony/dependency-injection ^4.4 | ^5.0 -> found symfony/dependency-injection[v4.4.0-BETA1, ..., v4.4.34, v5.0.0-BETA1, ..., v5.4.0] but these were not loaded, likely because it conflicts with another require.
```

### PR DESCRIPTION
**Pull request by amacrobert-meq**
Fixes #90

### CODE REVIEW

**Review by lahaxearnaud — DISMISSED** [review]

**Review by avareldev — APPROVED** [review]

**Comment by mssimi** [comment]
@amacrobert-meq  Can you merge it?

**Comment by amacrobert-meq** [comment]
@mssimi I cannot -- looks like required checks need to be run. Since I'm not a maintainer I can't do it myself.

@migo315 it looks like you're the main contributor. Can you give me access to what I need to keep this repo up to date?

**Comment by mKnoop** [comment]
Thanks for the contribution and sorry for the late reply. 

We will schedule this for the next release and try to check the pr next week.

**Review by mKnoop — APPROVED** [review]

**Comment by mKnoop** [comment]
I have merged the pr and we will create a new version with this symfony 6 support.

**Pull request merged**
