### PR TITLE
Port missing commit from v3.x to master

### PR DESCRIPTION
**Pull request by ajgarlag**
This PR ports a missing feature from `v3.x` to `master` and fix changelog

### CODE REVIEW

**Comment by migo315** [comment]
@ajgarlag There is one test failing, because the event "FilterControllerEvent" was renamed to "ControllerEvent" in Symfony 4/5. Can you fix your test?

```
1) Flagception\Tests\FlagceptionBundle\Listener\RoutingMetadataSubscriberTest::testRouteWithMultipleFeaturesIsNotActive
Failed asserting that exception of type "PHPUnit\Framework\MockObject\RuntimeException" matches expected exception "Symfony\Component\HttpKernel\Exception\NotFoundHttpException". Message was: "Cannot stub or mock class or interface "Flagception\Tests\FlagceptionBundle\Listener\FilterControllerEvent" which does not exist" at
/home/travis/build/bestit/flagception-bundle/tests/Listener/RoutingMetadataSubscriberTest.php:138
```

**Comment by ajgarlag** [comment]
@migo315 The new `ControllerEvent` class is declared final, so it cannot be mocked. I've instantiated a real event.

**Comment by ajgarlag** [comment]
@migo315 Test failures are unrelated to this PR. They are related to the new Xdebug 3.

See:
- https://github.com/bestit/flagception-bundle/pull/83/commits/6afadd67c15297df4acd07c13e494570d33ea6d9
- https://travis-ci.org/github/bestit/flagception-bundle/builds/747588452
- https://travis-ci.community/t/xdebug-3-is-installed-by-default-breaking-builds/10748/3
- https://github.com/xdebug/xdebug/pull/699

**Comment by migo315** [comment]
Thanks for your help! Great work! I take a look at the travis build later and merge this PR.

**Pull request merged**
